version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_foodalert
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: foodalert
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  nestjs:
    build: .
    container_name: nest_foodalert
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: foodalert
    depends_on:
      - postgres
    networks:
      - app_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  pgdata:

networks:
  app_network:
